server:
  port: 8085

spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  properties:
    hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect
    format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
api:
  prefix: api/v1